---
- hosts: all
  become: yes
  tasks:
  - name: install oepn jdk 9
    apt: 
      name: install tomcat server
      state: present
  - name: download the jenkins to webapp
    get_url: 
      url:  https://get.jenkins.io/war-stable/2.361.4/jenkins.war
      dest: /etc/tomcat9/jenkins.war
  - name: enable and start tomcat
    service: 
      name: tomcat
      state: started
      enabled: true



